/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffeshop;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;  
import java.lang.NullPointerException;

/**
 *
 * @author USER
 */
public class FormAdmin extends javax.swing.JFrame {
public Statement st; 
public ResultSet rs; 
public DefaultTableModel tabModel;
Connection cn = coffeshop.koneksi.koneksi ();
    /**
     * Creates new form FormAdmin
     */
public void judul(){
            Object [] judul = {
                "No.Pesanan", "Nama", "Nama Menu", "Instagram"
            };
            tabModel = new DefaultTableModel (null, judul);
            Tbpesanan.setModel(tabModel);
            }
    public void tampildata(String where){
    try{
        st = cn.createStatement();
        tabModel.getDataVector().removeAllElements();
        tabModel.fireTableDataChanged();
        rs = st.executeQuery("SELECT * FROM tbpesanan"+where);
        
        while (rs.next()){
            Object[] data = {
                rs.getString("id"),
                rs.getString("nama"),
                rs.getString("pesanan"),
                rs.getString("instagram"),
            };
            tabModel.addRow(data);
        }
    }catch (Exception e){
            e.printStackTrace();
        }
}
    public FormAdmin() {
        initComponents();
        judul();
        tampildata("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbpesanan = new javax.swing.JTable();
        selesai = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        menu = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        instagram = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard Kasir Jawir Cafe");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 12, 269, -1));

        Tbpesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbpesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbpesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbpesanan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 52, -1, -1));

        selesai.setBackground(new java.awt.Color(0, 255, 204));
        selesai.setText("Selesai");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });
        getContentPane().add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 323, 79, -1));

        edit.setBackground(new java.awt.Color(255, 255, 0));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 323, 79, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 125, -1, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 123, 177, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 172, -1, -1));

        menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih menu...", "kopi hitam manis", "kopi jawa asli", "kopi susu", "kopi gula aren", "kopi matcha latte", " " }));
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 170, 176, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Instagram");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 222, -1, -1));
        getContentPane().add(instagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 220, 176, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No.Meja");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 81, -1, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 79, 177, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 390, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setText("RE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 11, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\kopi1.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 820, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try{
            st = cn.createStatement();
            st.executeUpdate("UPDATE tbpesanan set "
            +"nama='" + nama.getText()+ "', "
            +"pesanan='" + menu.getSelectedItem()+"', "
            +"instagram='"+ instagram.getText()+"' where "+ "id='"+id.getText()+"'");
            tampildata("");
            JOptionPane.showMessageDialog(null, "Edit Berhasil");
            reset();
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_editActionPerformed

    private void TbpesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbpesananMouseClicked
        // TODO add your handling code here:
        id.setText(Tbpesanan.getValueAt(Tbpesanan.getSelectedRow(), 0).toString());
       nama.setText(Tbpesanan.getValueAt(Tbpesanan.getSelectedRow(), 1).toString());
       instagram.setText(Tbpesanan.getValueAt(Tbpesanan.getSelectedRow(), 3).toString());
       menu.setSelectedItem(Tbpesanan.getValueAt(Tbpesanan.getSelectedRow(), 2).toString());
       id.setEnabled(false);
       nama.setEnabled(false);
    }//GEN-LAST:event_TbpesananMouseClicked

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        // TODO add your handling code here:
        try{
            int jawab;
            
            if ((jawab = JOptionPane.showConfirmDialog(null, "Apakah Dia Sudah Selesai Transaksi", "konfirmasi", JOptionPane.YES_NO_OPTION))==0){
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM tbpesanan WHERE id='"
                +tabModel.getValueAt(Tbpesanan.getSelectedRow(), 0)+"'");
                tampildata("");
                reset();
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_selesaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DashboardLogin l = new DashboardLogin();
l.show();
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)Tbpesanan.getModel();
        model.setRowCount(0);
        tampildata("");
    }//GEN-LAST:event_jButton2ActionPerformed
public void reset(){
    id.setText("");
    nama.setText("");
    menu.setSelectedItem("");
    instagram.setText("");
    id.setEnabled(true);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbpesanan;
    private javax.swing.JButton edit;
    private javax.swing.JTextField id;
    private javax.swing.JTextField instagram;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> menu;
    private javax.swing.JTextField nama;
    private javax.swing.JButton selesai;
    // End of variables declaration//GEN-END:variables
}
